### ISSUE TITLE
Run command stuck

### ISSUE THREAD

**Issue by avnerbarr** [Swiftline/Swiftline#21] opened 2016-06-30 14:59 UTC
I'm running in it seems to not do anything (it is a long running command but it seems to never finish)

If I run the command from the command line terminal it does complete

Is there a way to continually output the stdout (Not wait for the result)

let archiveCommand = "some command to run"
let res = run(archiveCommand) // never completing through my script

**Comment by nsomar** [comment] 2016-09-27 19:27
I think that this was solved with #25 
Could you please give it a try again and let me know :)?

I will close this, but please do reopen it if it persits

**Closed as completed by nsomar** 2016-09-27 19:27 UTC

**Comment by CraigSiemens** [comment] 2016-11-21 00:54
I just ran into this same issue using master. For me, it was caused by ffmpeg thinking there was more input comping through stdin. I've found two possible solutions.

Run my script  and close stdin with
```
myScript <&-
```

or in `ActualTaskExecutor` `execute` add
```
task.standardInput = FileHandle.nullDevice
```

**Comment by nsomar** [comment] 2016-11-21 00:58
@CraigSiemens @avnerbarr I did refactor the process execution functionality in SwiftLine and extracted it to another library https://github.com/oarrabi/Runner

This new library is POSIX compliant, it uses `posix_spawn` under the hood, so it should provide more consistent behaviours.

It is functional, but still in working progress. I would love if you give it a try :)

**Comment by CraigSiemens** [comment] 2016-12-04 23:09
I finally got around to giving Runner a try and it worked like a charm. Thanks!

**Comment by nsomar** [comment] 2016-12-04 23:19
@CraigSiemens Thats awesome to hear :) thanks for trying it!
